"""Generate spotify/trust_anchors.h (BearSSL br_x509_trust_anchor table) from certs/*.pem.

Run from the repository root: python scripts/gen_trust_anchors.py
Only the subject DN and public key are taken from each root; no validity is
embedded (BearSSL does not check anchor expiry).
"""
from pathlib import Path
import base64
import re

ROOT = Path(__file__).resolve().parents[1]
OID_RSA = bytes.fromhex("2a864886f70d010101")
OID_EC = bytes.fromhex("2a8648ce3d0201")
CURVES = {
    bytes.fromhex("2a8648ce3d030107"): "BR_EC_secp256r1",
    bytes.fromhex("2b81040022"): "BR_EC_secp384r1",
    bytes.fromhex("2b81040023"): "BR_EC_secp521r1",
}


def tlv(data, pos):
    """Return (tag, content_start, content_end) for the DER element at pos."""
    tag = data[pos]
    length = data[pos + 1]
    pos += 2
    if length & 0x80:
        count = length & 0x7F
        length = int.from_bytes(data[pos:pos + count], "big")
        pos += count
    return tag, pos, pos + length


def children(data, start, end):
    out = []
    while start < end:
        tag, c0, c1 = tlv(data, start)
        out.append((tag, start, c0, c1))
        start = c1
    return out


def anchor(der):
    _, c0, c1 = tlv(der, 0)                      # Certificate
    tbs = children(der, c0, c1)[0]
    fields = children(der, tbs[2], tbs[3])
    if fields[0][0] == 0xA0:                     # explicit version
        fields = fields[1:]
    # serial, signature, issuer, validity, subject, subjectPublicKeyInfo
    subject = fields[4]
    spki = fields[5]
    dn = der[subject[1]:subject[3]]
    alg, key = children(der, spki[2], spki[3])
    alg_parts = children(der, alg[2], alg[3])
    oid = der[alg_parts[0][2]:alg_parts[0][3]]
    bits = der[key[2] + 1:key[3]]                # skip unused-bits byte
    if oid == OID_RSA:
        _, k0, k1 = tlv(bits, 0)
        n, e = children(bits, k0, k1)
        modulus = bits[n[2]:n[3]].lstrip(b"\x00")
        exponent = bits[e[2]:e[3]].lstrip(b"\x00")
        return dn, ("rsa", modulus, exponent)
    if oid == OID_EC:
        curve = der[alg_parts[1][2]:alg_parts[1][3]]
        return dn, ("ec", CURVES[curve], bits)
    raise ValueError("unsupported key type")


def c_bytes(name, data):
    rows = [", ".join(f"0x{b:02X}" for b in data[i:i + 12]) for i in range(0, len(data), 12)]
    return f"static const unsigned char {name}[] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


def main():
    pems = sorted((ROOT / "certs").glob("*.pem"))
    out = ["/* Generated by scripts/gen_trust_anchors.py from the PEM files in certs/. Do not edit. */",
           "#ifndef SPOTIFY_TRUST_ANCHORS_H", "#define SPOTIFY_TRUST_ANCHORS_H", "",
           "#include <bearssl.h>", ""]
    entries = []
    for index, pem in enumerate(pems):
        body = re.search(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----",
                         pem.read_text(), re.S).group(1)
        dn, key = anchor(base64.b64decode("".join(body.split())))
        out.append(f"/* {pem.name} */")
        out.append(c_bytes(f"TA{index}_DN", dn))
        if key[0] == "rsa":
            out.append(c_bytes(f"TA{index}_RSA_N", key[1]))
            out.append(c_bytes(f"TA{index}_RSA_E", key[2]))
            pkey = (f"{{ BR_KEYTYPE_RSA, {{ .rsa = {{ (unsigned char *)TA{index}_RSA_N, "
                    f"sizeof TA{index}_RSA_N, (unsigned char *)TA{index}_RSA_E, "
                    f"sizeof TA{index}_RSA_E }} }} }}")
        else:
            out.append(c_bytes(f"TA{index}_EC_Q", key[2]))
            pkey = (f"{{ BR_KEYTYPE_EC, {{ .ec = {{ {key[1]}, (unsigned char *)TA{index}_EC_Q, "
                    f"sizeof TA{index}_EC_Q }} }} }}")
        entries.append(f"    {{ {{ (unsigned char *)TA{index}_DN, sizeof TA{index}_DN }},\n"
                       f"      BR_X509_TA_CA,\n      {pkey} }}")
    out.append("static const br_x509_trust_anchor TAs[] = {")
    out.append(",\n".join(entries))
    out.append("};")
    out.append("")
    out.append(f"#define TAs_NUM {len(entries)}")
    out.append("")
    out.append("#endif /* SPOTIFY_TRUST_ANCHORS_H */")
    (ROOT / "spotify" / "trust_anchors.h").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {len(entries)} anchors")


if __name__ == "__main__":
    main()
