#include "config.h"
#include "log.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <pspdebug.h>

static void trim(char *s)
{
    char *p = s;
    while (isspace((unsigned char)*p)) p++;
    if (p != s) memmove(s, p, strlen(p) + 1);

    size_t len = strlen(s);
    while (len > 0 && isspace((unsigned char)s[len - 1])) {
        s[--len] = '\0';
    }
}

static int hex_to_bytes(const char *hex, uint8_t *out, size_t max_out)
{
    size_t len = strlen(hex);
    if ((len % 2) != 0 || (len / 2) > max_out) return -1;
    for (size_t i = 0; i < len / 2; ++i) {
        unsigned int byte_val = 0;
        if (sscanf(&hex[i * 2], "%02x", &byte_val) != 1) return -1;
        out[i] = (uint8_t)byte_val;
    }
    return (int)(len / 2);
}

/* <app dir>/spotify.cfg: absolute, because the sceIoChdir directory is not
 * seen by other threads (the player thread reloads and saves the config). */
static char app_cfg_path[300];

void spotify_config_set_dir(const char *dir)
{
    int n = snprintf(app_cfg_path, sizeof app_cfg_path, "%s/spotify.cfg", dir);
    if (n < 0 || (size_t)n >= sizeof app_cfg_path) app_cfg_path[0] = '\0';
}

int spotify_config_load(spotify_config *cfg)
{
    const char *candidate_paths[] = {
        app_cfg_path[0] ? app_cfg_path : "spotify.cfg",
        "spotify.cfg",
        "ms0:/PSP/GAME/PSPOTIFY/spotify.cfg",
        "ms0:/spotify.cfg"
    };

    memset(cfg, 0, sizeof(*cfg));
    FILE *f = NULL;

    for (size_t i = 0; i < sizeof(candidate_paths) / sizeof(candidate_paths[0]); ++i) {
        f = fopen(candidate_paths[i], "r");
        if (f) {
            strncpy(cfg->path, candidate_paths[i], sizeof(cfg->path) - 1);
            break;
        }
    }

    if (!f) {
        log_printf("CFG: No spotify.cfg found on Memory Stick!\n");
        return -1;
    }

    char line[2048];
    while (fgets(line, sizeof(line), f)) {
        trim(line);
        if (line[0] == '#' || line[0] == ';' || line[0] == '\0') continue;

        char *eq = strchr(line, '=');
        if (!eq) continue;

        *eq = '\0';
        char *key = line;
        char *val = eq + 1;
        trim(key);
        trim(val);

        if (strcmp(key, "username") == 0) {
            strncpy(cfg->username, val, sizeof(cfg->username) - 1);
        } else if (strcmp(key, "token") == 0) {
            strncpy(cfg->token, val, sizeof(cfg->token) - 1);
        } else if (strcmp(key, "password") == 0) {
            strncpy(cfg->password, val, sizeof(cfg->password) - 1);
        } else if (strcmp(key, "refresh_token") == 0) {
            strncpy(cfg->refresh_token, val, sizeof(cfg->refresh_token) - 1);
        } else if (strcmp(key, "blob_client") == 0) {
            strncpy(cfg->blob_client, val, sizeof(cfg->blob_client) - 1);
        } else if (strcmp(key, "blob") == 0) {
            int bytes = hex_to_bytes(val, cfg->blob, sizeof(cfg->blob));
            if (bytes > 0) cfg->blob_len = (size_t)bytes;
        }
    }
    fclose(f);

    /* Determine auth type priority: Stored Blob > Token > Password */
    if (cfg->blob_len > 0) {
        cfg->auth_type = AUTH_TYPE_STORED_CREDENTIALS;
        log_printf("CFG: Loaded stored credentials blob (%u bytes)\n", (unsigned int)cfg->blob_len);
    } else if (strlen(cfg->token) > 0) {
        cfg->auth_type = AUTH_TYPE_SPOTIFY_TOKEN;
        log_printf("CFG: Loaded access token (%u chars)\n", (unsigned int)strlen(cfg->token));
    } else if (strlen(cfg->password) > 0) {
        cfg->auth_type = AUTH_TYPE_USER_PASS;
        log_printf("CFG: Loaded user/pass for '%s'\n", cfg->username);
    } else if (cfg->refresh_token[0]) {
        /* The access token is filled in from the refresh token at startup. */
        cfg->auth_type = AUTH_TYPE_SPOTIFY_TOKEN;
    } else {
        log_printf("CFG: Neither token, blob nor password found!\n");
        return -2;
    }

    return 0;
}

int spotify_config_save_blob(const spotify_config *cfg, const char *canonical_username, const uint8_t *blob, size_t blob_len)
{
    const char *target = cfg->path[0] ? cfg->path
                       : app_cfg_path[0] ? app_cfg_path : "spotify.cfg";
    FILE *f = fopen(target, "w");
    if (!f) {
        f = fopen("ms0:/PSP/GAME/PSPOTIFY/spotify.cfg", "w");
    }
    if (!f) {
        log_printf("CFG: Failed to save reusable blob to Memory Stick!\n");
        return -1;
    }

    fprintf(f, "# Spotify credentials (auto-generated by PSP)\n");
    if (canonical_username && canonical_username[0]) {
        fprintf(f, "username = %s\n", canonical_username);
    } else if (cfg->username[0]) {
        fprintf(f, "username = %s\n", cfg->username);
    }

    if (cfg->refresh_token[0]) fprintf(f, "refresh_token = %s\n", cfg->refresh_token);
    if (blob_len > 0 && cfg->blob_client[0]) fprintf(f, "blob_client = %s\n", cfg->blob_client);

    fprintf(f, "blob = ");
    for (size_t i = 0; i < blob_len; ++i) {
        fprintf(f, "%02x", blob[i]);
    }
    fprintf(f, "\n");
    fclose(f);

    log_printf("CFG: Reusable auth blob saved to %s!\n", target);
    return 0;
}
